site_name: Jade
repo_name: Jade
repo_url: https://github.com/Snownee/Jade
site_author: Snownee
edit_uri: ''

nav:
  - 'Preface': README.md
  - '1.20+':
      - 'Getting Started': plugins20/getting-started.md
      - 'Overrides': plugins20/overrides.md
      - 'Hiding Target': plugins20/hiding-target.md
      - 'Plugin Configuration': plugins20/plugin-config.md
  - '1.19 and Fabric 1.17-1.18':
      - 'Getting Started': plugins19/getting-started.md
      - 'Overrides': plugins19/overrides.md
      - 'Hiding Target': plugins19/hiding-target.md
      - 'Plugin Configuration': plugins19/plugin-config.md
  - 'Forge 1.17-1.18':
      - 'Getting Started': plugins17/getting-started.md
      - 'Overrides': plugins17/overrides.md
      - 'Hiding Target': plugins17/hiding-target.md
  - 'Custom Theme':
      - '1.20.2+': themes/v3.md
      - '1.20.1': themes/v2.md
  - 'Datapack Support':
      - '1.20.5+': datapacks/block21.md
      - '1.18-1.20.4': datapacks/block.md
  - 'Upgrading Guides':
      - '1.20 -> 1.21': changes/121.md
      - '1.19 -> 1.20': changes/120.md
      - '1.18 -> 1.19': changes/119.md
      - '1.16 -> 1.17': changes/117.md
      - '1.20.4 -> 1.20.5': changes/1205.md
      - '1.20.1 -> 1.20.2': changes/1202.md

theme:
  name: material
  language: en
  logo: images/site_icon.png
  favicon: images/site_icon.png
  features:
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - awesome-pages
